### ISSUE TITLE
Please package latest to support python 3 and send it up to pypi?

### ISSUE THREAD

**Issue by rootsmith** [benhodgson/baluhn#3]
The current version of baluhn out on pypi doesn't support python 3. The latest on the master branch works fabulously. Is there any way you can push that out to pypi as another version? Thanks.

**Comment by tarkatronic** [comment]
Is there any chance of this happening? We're having to copy the module into our code rather than relying on pip.

**Comment by paulfurley** [comment]
That would indeed be wonderful :+1:

**Comment by flowersw** [comment]
Yes, agreed.

**Comment by whyscream** [comment]
I've just released a new version of the `baluhn` package to pypi, supporting both python2 and python3, `baluhn 0.1.2` (0.1.1 release had an installer bug for python2).

Please try it.

**Comment by benhodgson** [comment]
Thank you so much!
